### ISSUE TITLE
NftClientImpl giving error: Required method implementation missing

### ISSUE THREAD

**Issue by manishdait** [OpenElements/hiero-enterprise-java#128]
`NftClientImpl` currently implements `NftClient`, which has methods like `createNftType and associateNft` for creating NFT tokens. However, it also extends `TokenClient`, which defines methods `createToken and associateToken` that are not currently implemented. This is causing an error due to a missing required method implementation.

A potential solution might be  to rename `createNftType` and `associateNft` to `createToken` and `associateToken`, respectively, to align with the TokenClient interface.

**Comment by hendrikebbers** [comment]
Thank you. That was a lousy merge I did. I just fixed it.
